import {
  ClipboardList,
  Briefcase,
  Users,
  FolderKanban,
  Award,
} from 'lucide-react';

export const EXPERIENCE_CATEGORIES = {
  Magang: {
    type: 'Formal',
    icon: Briefcase,
    title: 'Detail Magang',
    subtitle: 'Kelola semua pengalaman magang yang telah Anda jalani.',
    listTitle: 'Daftar Magang',
    addLabel: 'Tambah Magang',
    editTitle: 'Edit Magang',
    previewTitle: 'Preview Magang',
    emptyText: 'Belum ada data magang.',
    selectText: 'Pilih magang dari daftar di sebelah kiri.',
    deleteConfirm: 'Hapus data magang ini?',
    toastAdd: 'Magang ditambahkan',
    toastUpdate: 'Magang diperbarui',
    toastDelete: 'Magang dihapus',
  },
  Jobdesk: {
    type: 'Formal',
    icon: ClipboardList,
    title: 'Detail Jobdesk',
    subtitle: 'Kelola semua pengalaman jobdesk yang telah Anda jalani.',
    listTitle: 'Daftar Jobdesk',
    addLabel: 'Tambah Jobdesk',
    editTitle: 'Edit Jobdesk',
    previewTitle: 'Preview Jobdesk',
    emptyText: 'Belum ada data jobdesk.',
    selectText: 'Pilih jobdesk dari daftar di sebelah kiri.',
    deleteConfirm: 'Hapus data jobdesk ini?',
    toastAdd: 'Jobdesk ditambahkan',
    toastUpdate: 'Jobdesk diperbarui',
    toastDelete: 'Jobdesk dihapus',
  },
  Organisasi: {
    type: 'Informal',
    icon: Users,
    title: 'Detail Organisasi',
    subtitle: 'Kelola semua pengalaman organisasi yang telah Anda jalani.',
    listTitle: 'Daftar Organisasi',
    addLabel: 'Tambah Organisasi',
    editTitle: 'Edit Organisasi',
    previewTitle: 'Preview Organisasi',
    emptyText: 'Belum ada data organisasi.',
    selectText: 'Pilih organisasi dari daftar di sebelah kiri.',
    deleteConfirm: 'Hapus data organisasi ini?',
    toastAdd: 'Organisasi ditambahkan',
    toastUpdate: 'Organisasi diperbarui',
    toastDelete: 'Organisasi dihapus',
  },
  'Proyek Kelompok': {
    type: 'Informal',
    icon: FolderKanban,
    title: 'Detail Proyek Kelompok',
    subtitle: 'Kelola semua pengalaman proyek kelompok yang telah Anda jalani.',
    listTitle: 'Daftar Proyek Kelompok',
    addLabel: 'Tambah Proyek',
    editTitle: 'Edit Proyek Kelompok',
    previewTitle: 'Preview Proyek',
    emptyText: 'Belum ada data proyek kelompok.',
    selectText: 'Pilih proyek dari daftar di sebelah kiri.',
    deleteConfirm: 'Hapus data proyek ini?',
    toastAdd: 'Proyek ditambahkan',
    toastUpdate: 'Proyek diperbarui',
    toastDelete: 'Proyek dihapus',
  },
  'Sertifikat & Kursus': {
    type: 'Informal',
    icon: Award,
    title: 'Detail Sertifikat & Kursus',
    subtitle: 'Kelola semua sertifikat dan kursus yang telah Anda selesaikan.',
    listTitle: 'Daftar Sertifikat & Kursus',
    addLabel: 'Tambah Sertifikat',
    editTitle: 'Edit Sertifikat & Kursus',
    previewTitle: 'Preview Sertifikat',
    emptyText: 'Belum ada data sertifikat & kursus.',
    selectText: 'Pilih sertifikat dari daftar di sebelah kiri.',
    deleteConfirm: 'Hapus data sertifikat ini?',
    toastAdd: 'Sertifikat ditambahkan',
    toastUpdate: 'Sertifikat diperbarui',
    toastDelete: 'Sertifikat dihapus',
  },
};

export function getCategoryConfig(category) {
  return EXPERIENCE_CATEGORIES[category] || EXPERIENCE_CATEGORIES.Jobdesk;
}
